name: agentMET4FOF
channels:
    - defaults
    - conda-forge
dependencies:
    - python >= 3.7
    - ipykernel
    - numpy
    - scikit-learn
    - scikit-multiflow
    - scipy
    - matplotlib
    - pandas
    - seaborn
    - dash
    - networkx
    - multiprocess
    - h5py
    - requests
    # pip dependencies have to be provided in `requirements.txt` syntax
    - pip:
        - -r requirements.txt
